### ISSUE TITLE
Annotator not accepting input

### ISSUE THREAD

**Issue by DLWheeler** [biolab/orange3-bioinformatics#287]
**Describe the bug**

When using the example workflow at:

https://orangedatamining.com/widget-catalog/bioinformatics/annotate_projection/

The annotator widget emits an error when the output of the tSNE widget is connected.

**To Reproduce**
1. Set up workflow as directed in the tutorial at the URL above
2. Get the error when connecting tSNE to Annotator

**Expected behavior**
I expected the Annotator to work as in the example.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Python Version: 3.8
 - Orange Version 3.29.3
 - Add-on Version 4.40

**Additional context**

The error I get is:

2021-07-30 15:56:17,343:INFO:orangecanvas.scheme.scheme: Added link 't-SNE' ('Data') -> 'Annotator' ('Reference Data') to scheme ''.
2021-07-30 15:56:17,343:INFO:orangecanvas.scheme.signalmanager: Scheduling signal data update for 'SchemeLink((t-SNE, Data) -> (Annotator, Reference Data))'.
-------------------------- AssertionError Exception ---------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1024, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1062, in __process_next_helper
    self.process_node(selected_node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 690, in process_node
    self.send_to_node(node, signals_in)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 806, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 820, in process_signals_for_widget
    process_signals_for_widget(widget, signals, workflow)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 921, in process_signals_for_widget
    process_signal_input(input_meta, widget, signal, workflow)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 875, in process_signal_input_default
    assert old.link == signal.link
AssertionError
-------------------------------------------------------------------------------

**Comment by JakaKokosar** [comment]
Or better yet, please use the latest released version of Orange and see if the problem is still present.

**Comment by DLWheeler** [comment]
OK, I do not see the problem after upgrading to Orange version 3.30.
Thanks, this workflow will be very useful to me!

    On Wednesday, October 6, 2021, 08:29:08 AM EDT, Jaka ***@***.***> wrote:  
 
 


Or better yet, please use the latest released version of Orange and see if the problem is still present.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
