### ISSUE TITLE
dictyExpress not working 

### ISSUE THREAD

**Issue by robertcv** [biolab/orange3-bioinformatics#303]
**Describe the bug**
dictyExpress widget crashes immediately after placing it on the canvas. Trying to double-click it and it won't even show its GUI but the error appears instead. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.10
 - Orange Version: master
 - Add-on Version: master

**Comment by JakaKokosar** [comment]
@robertcv, can you please provide more details? It would help to know what error log prints out.

**Comment by robertcv** [comment]
Sorry. I thought that widget is outdated or something like that and that it probably doesn't work for everybody. I can normally open the mentioned ulr in a browser. My error:

```
Traceback (most recent call last):
  File "*/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "*/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "*/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "*/venv/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "*/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "*/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "*/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "*/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dictyexpress.research.bcm.edu', port=443): Max retries exceeded with url: /user/ajax/login/ (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*/venv/lib/python3.8/site-packages/genesis/genesis.py", line 392, in __init__
    request = requests.post(url + '/user/ajax/login/', data=payload)
  File "*/venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "*/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "*/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "*/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "*/venv/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dictyexpress.research.bcm.edu', port=443): Max retries exceeded with url: /user/ajax/login/ (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "*-bioinformatics/orangecontrib/bioinformatics/resolwe/__init__.py", line 44, in connect
    return _api(username, password, url)
  File "*-bioinformatics/orangecontrib/bioinformatics/resolwe/genapi.py", line 24, in __init__
    self._gen = Genesis(email, password, url)
  File "*/venv/lib/python3.8/site-packages/genesis/genesis.py", line 35, in __init__
    self.auth = GenAuth(email, password, url)
  File "*/venv/lib/python3.8/site-packages/genesis/genesis.py", line 394, in __init__
    raise Exception('Server not accessible on {}'.format(url))
Exception: Server not accessible on https://dictyexpress.research.bcm.edu

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "*/venv/lib/python3.8/site-packages/orangecanvas/scheme/widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "*/venv/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "*/venv/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "*-bioinformatics/orangecontrib/bioinformatics/widgets/OWdictyExpress.py", line 123, in __init__
    self.sign_in(silent=True)
  File "*-bioinformatics/orangecontrib/bioinformatics/widgets/OWdictyExpress.py", line 151, in sign_in
    self.res = connect(**self.genapi_pub_auth, server_type=resolwe.GENESIS_PLATFORM)
  File "*-bioinformatics/orangecontrib/bioinformatics/resolwe/__init__.py", line 46, in connect
    raise ResolweAuthError(e.args[0]) from e
orangecontrib.bioinformatics.resolwe.ResolweAuthError: Server not accessible on https://dictyexpress.research.bcm.edu
```
