### ISSUE TITLE
Annotate widget crashes after generating results

### ISSUE THREAD

**Issue by DLWheeler** [biolab/orange3-bioinformatics#312]
After providing t-SNE 'Data" as 'Reference data" and a list of marker genes as "Genes" to the Annotator widget, it correctly generates the annotation graphic and gives the progress as 100% but then continues to run (run indicator continues to circle) and stalls the workflow.  Using the basic example given in the help for the Annotator widget will generate the stall.  The error log gives:

`/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/metrics/pairwise.py:1429: UserWarning: Multiprocessing-backed parallel loops cannot be nested below threads, setting n_jobs=1
  if effective_n_jobs(n_jobs) == 1:
--------------------------- RuntimeError Exception ----------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/utils/concurrent.py", line 591, in _on_task_done
    super()._on_task_done(future)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/utils/concurrent.py", line 549, in _on_task_done
    self.on_done(future.result())
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/bioinformatics/widgets/OWAnnotateProjection.py", line 589, in on_done
    self.commit()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/gui.py", line 1839, in __call__
    raise RuntimeError(
RuntimeError: This function is deferred; explicitly call commit.deferred or commit.now`

I'm running Orange 3.32 on a MacBook Pro (2015),  OSx 12.4

**Comment by JakaKokosar** [comment]
Fixed in https://github.com/biolab/orange3-bioinformatics/pull/308
