### ISSUE TITLE
taxonomy does not work with older pythons

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange3-bioinformatics#38]
On my system 3.4 Python (Ubuntu 14.04) the taxonomy does not work:
```
Traceback (most recent call last):
  File "/home/marko/orange3-bioinformatics/orangecontrib/bioinformatics/ncbi/taxonomy/utils.py", line 359, in <module>
    main()
  File "/home/marko/orange3-bioinformatics/orangecontrib/bioinformatics/ncbi/taxonomy/utils.py", line 354, in main
    strains = test.get_all_strains("562")
  File "/home/marko/orange3-bioinformatics/orangecontrib/bioinformatics/ncbi/taxonomy/utils.py", line 112, in get_all_strains
    return self._tax.strains(tax_id)
  File "/home/marko/orange3-bioinformatics/orangecontrib/bioinformatics/ncbi/taxonomy/utils.py", line 218, in strains
    """, (tax_id, ))
sqlite3.OperationalError: near "WITH": syntax error
```
My `sqlite3.sqlite_version` is 3.8.2. The WITH statement is only supported since 3.8.3.

**Comment by JakaKokosar** [comment]
@markotoplak Hey, is this still relevant? If I'm not mistaken Orange3 does not support python versions that are older than 3.5.
